### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by tonyrog** [patrickdown/HelloT5Cube#1]
Hi! Thank you for the T5Cube. I wrote a Makefile to be able to compile it on linux/ubuntu.
There where a few issues, but really pretty straight forward. 
I have not tested yet, but will soon. Now it compiles and the GL windows pops up.
You can check it out in my fork. Tell me if you want a pull request.
Question. I checked in TiltFive/lib/linux/x86_64/libTiltFiveNative.so but the 1.4.1 version with linux support, 
do you think it the main code should be updated to 1.4.1 as well?
/Tony

**Comment by patrickdown** [comment]
It should probably be updated to 1.4.1. This project is pretty old. I wrote it way before the Godot plugin. Your fork looks good. Go ahead and submit a pull request if you like.

**Comment by tonyrog** [comment]
Did you want it or ?

**Comment by patrickdown** [comment]
Yeah, I just merged it.
